"""Campaign summary: the tables a paper would actually print.

Pulls every run from `reports_sota/runs_index.csv`, pairs the runs that are
supposed to be compared, and runs the paired significance tests. Written as a
module rather than done by hand because the campaign's whole point is that
hand-comparison across runs is where the errors came from: R3's "pruning helps"
had the wrong sign until it was measured in-run, and R5's "c364 is degrading"
was an artefact of one hard partition.

    python -m src.sota_summary            # prints markdown, writes SUMMARY.md
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from .config import RESEARCH_ROOT

REPORTS = RESEARCH_ROOT / "reports_sota"

# Origin paper, best reported fusion result (random 80/20 + SMOTE).
PAPER_WEIGHTED_F1 = 0.72
# Prior leaky-protocol baseline already in this repo (decision_fusion + RF).
PRIOR_REPO_MACRO_F1 = 0.728
MAJORITY_ALL700 = 0.344


def fold_scores(run: str, scope: str = "all700") -> np.ndarray:
    """Per-fold macro F1 for one run, from its report table."""
    p = REPORTS / run / "report.md"
    if not p.exists():
        return np.array([])
    txt = p.read_text(encoding="utf-8")
    marker = f"## Per-fold — {scope}"
    if marker not in txt:
        return np.array([])
    block = txt.split(marker)[1].split("\n## ")[0]
    out = []
    for line in block.strip().splitlines():
        if not line.startswith("| ") or line.startswith("|---") or "n_test" in line:
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        # macro_f1 sits after fold, n_test, thr, n_members, n_members_full
        for c in cells[4:8]:
            try:
                v = float(c)
            except ValueError:
                continue
            if 0.2 < v < 1.0:
                out.append(v)
                break
    return np.array(out)


def paired(a: str, b: str, scope: str = "all700") -> dict | None:
    """Paired comparison of two runs that share a partition."""
    x, y = fold_scores(a, scope), fold_scores(b, scope)
    n = min(len(x), len(y))
    if n < 3:
        return None
    x, y = x[:n], y[:n]
    d = x - y
    t, pt = stats.ttest_rel(x, y)
    try:
        _, pw = stats.wilcoxon(x, y)
    except Exception:
        pw = float("nan")
    # 95% CI on the mean paired difference
    se = d.std(ddof=1) / np.sqrt(n)
    crit = stats.t.ppf(0.975, n - 1)
    return {"a": a, "b": b, "scope": scope, "n_folds": n,
            "mean_a": float(x.mean()), "mean_b": float(y.mean()),
            "delta": float(d.mean()),
            "ci_low": float(d.mean() - crit * se),
            "ci_high": float(d.mean() + crit * se),
            "wins": int((d > 0).sum()),
            "t_p": float(pt), "wilcoxon_p": float(pw)}


def registry() -> pd.DataFrame:
    f = REPORTS / "runs_index.csv"
    return pd.read_csv(f) if f.exists() else pd.DataFrame()


def _fmt(v, nd=4):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) and v == v else "—"


def build() -> str:
    reg = registry()
    lines = ["# SOTA campaign — summary tables", "",
             "Generated by `python -m src.sota_summary`.", "",
             "> **Protocol.** Subject-shared repeated stratified CV, the split",
             "> rule the StressID origin paper uses. Subjects appear on both",
             "> sides; scores are inflated by subject leakage by a margin this",
             "> repo measured separately (see `LEAKY_PROTOCOL.md`). These numbers",
             "> are comparable to published ones and **not** to the",
             "> subject-held-out track in `reports/`.", ""]

    # ---- round progression on the searched partition
    order = ["s1_baseline_raw", "s2_views_relz", "s3_prune", "s4_windows", "s5_final"]
    lines += ["## 1. Round progression (seed 42 — the partition the search used)", "",
              "| Run | Macro F1 | Weighted F1 | Accuracy | ROC AUC |",
              "|---|---|---|---|---|"]
    for r in order:
        row = reg[reg.run_name == r]
        if row.empty:
            continue
        row = row.iloc[0]
        lines.append(f"| `{r}` | {_fmt(row.get('all700_macro_f1'))} | "
                     f"{_fmt(row.get('all700_weighted_f1'))} | "
                     f"{_fmt(row.get('all700_accuracy'))} | "
                     f"{_fmt(row.get('all700_roc_auc'))} |")
    lines += ["", "These are **not** the numbers to publish: all five rounds",
              "selected against this one partition, so the maximum over it is",
              "optimistically biased. Section 3 quantifies by how much.", ""]

    # ---- paired comparisons
    lines += ["## 2. Paired comparisons (identical folds)", "",
              "| Comparison | Scope | Folds | A | B | Δ | 95% CI | Wins | t p | Wilcoxon p |",
              "|---|---|---|---|---|---|---|---|---|---|"]
    pairs = [("s8a_final_r3", "s8b_base_r3", "all700"),
             ("s6_confirm_seed101", "s7_baseline_seed101", "all700"),
             ("s6_confirm_seed101", "s7_baseline_seed101", "c364")]
    for a, b, sc in pairs:
        r = paired(a, b, sc)
        if not r:
            continue
        lines.append(
            f"| `{a}` vs `{b}` | {sc} | {r['n_folds']} | {_fmt(r['mean_a'])} | "
            f"{_fmt(r['mean_b'])} | **{r['delta']:+.4f}** | "
            f"[{r['ci_low']:+.4f}, {r['ci_high']:+.4f}] | {r['wins']}/{r['n_folds']} | "
            f"{r['t_p']:.4f} | {r['wilcoxon_p']:.4f} |")
    lines += ["", "A confidence interval spanning zero means the round-by-round",
              "gains are not individually established at this fold count. That is",
              "reported rather than hidden: the defensible claim is about the",
              "pipeline as a whole, not each increment.", ""]

    # ---- selection bias
    lines += ["## 3. Campaign selection bias", "",
              "| Configuration | Partition | Macro F1 |", "|---|---|---|"]
    for run, part in (("s5_final", "seed 42 — searched"),
                      ("s6_confirm_seed101", "seed 101 — unseen")):
        row = reg[reg.run_name == run]
        if not row.empty:
            lines.append(f"| final | {part} | {_fmt(row.iloc[0].get('all700_macro_f1'))} |")
    f5 = reg[reg.run_name == "s5_final"]
    f6 = reg[reg.run_name == "s6_confirm_seed101"]
    if not f5.empty and not f6.empty:
        bias = f5.iloc[0]["all700_macro_f1"] - f6.iloc[0]["all700_macro_f1"]
        lines += ["", f"**Measured selection bias: {bias:+.4f} macro F1.** Five rounds "
                  "of choosing against one partition bought this much apparent "
                  "score that does not transfer.", ""]

    # ---- reference points
    lines += ["## 4. Against published work", "",
              "| Source | Protocol | Weighted F1 | Macro F1 |", "|---|---|---|---|",
              f"| StressID paper (SVM + average-rule fusion) | random 80/20 + SMOTE | "
              f"**{PAPER_WEIGHTED_F1:.2f}** | not reported |",
              f"| This repo, prior `decision_fusion+rf` | random 80/20 | 0.726 | "
              f"{PRIOR_REPO_MACRO_F1:.3f} |"]
    for run, label in (("s5_final", "**This campaign** (searched partition)"),
                       ("s6_confirm_seed101", "**This campaign** (unseen partition)")):
        row = reg[reg.run_name == run]
        if not row.empty:
            row = row.iloc[0]
            lines.append(f"| {label} | subject-shared 5-fold | "
                         f"{_fmt(row.get('all700_weighted_f1'), 3)} | "
                         f"{_fmt(row.get('all700_macro_f1'), 3)} |")
    lines += [f"| Majority class | — | — | {MAJORITY_ALL700:.3f} |", "",
              "The paper's 0.72 is a weighted F1 under a random 80/20 split with",
              "SMOTE; ours is a weighted F1 under subject-shared 5-fold CV without",
              "SMOTE. Same family of protocol, not an identical one, and the",
              "comparison should be described that way rather than as a",
              "like-for-like win.", ""]
    return "\n".join(lines)


def main() -> None:
    md = build()
    out = REPORTS / "SUMMARY.md"
    out.write_text(md, encoding="utf-8")
    print(md)
    print(f"\n[summary] -> {out}")


if __name__ == "__main__":
    main()
